services:
  postgres:
    image: postgres:16-alpine
    container_name: worklog-postgres
    environment:
      POSTGRES_DB: worklog
      POSTGRES_USER: worklog
      POSTGRES_PASSWORD: worklog123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worklog -d worklog"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: worklog-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/worklog
      KC_DB_USERNAME: worklog
      KC_DB_PASSWORD: worklog123
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: start-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/worklog-realm.json

volumes:
  postgres_data:
