version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: worklog-postgres
    environment:
      POSTGRES_DB: worklog
      POSTGRES_USER: worklog
      POSTGRES_PASSWORD: worklog123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worklog -d worklog"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: worklog-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: worklog
      KC_DB_PASSWORD: worklog123
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: start-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: worklog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    container_name: worklog-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://worklog:worklog123@postgres:5432/worklog
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: worklog
      KEYCLOAK_CLIENT_ID: worklog-api
      KEYCLOAK_CLIENT_SECRET: your-client-secret
      JWT_SECRET: your-jwt-secret
      REDIS_URL: redis://redis:6379
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../../apps/api:/app
      - /app/node_modules
    command: npm run dev

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    container_name: worklog-web
    environment:
      VITE_API_URL: http://localhost:3001/api/v1
      VITE_KEYCLOAK_URL: http://localhost:8080
      VITE_KEYCLOAK_REALM: worklog
      VITE_KEYCLOAK_CLIENT_ID: worklog-web
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ../../apps/web:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
  redis_data: